/*
 *Componentes:
*   Emanuel Basílio da Silva (20251134040033) 
    Matheus do Nascimento da Silva (20251134040023)
    RENATO ARAUJO GRILO (20251134040018)
    Thiago Tomaz de Araújo (20251134040031)
 */
package br.com.contas.exercicio_02.main;

import br.com.contas.exercicio_02.model.classes.ContaCorrente;
import br.com.contas.exercicio_02.model.classes.ContaPoupanca;
import br.com.contas.exercicio_02.services.OperacoesBancarias;
import br.com.contas.exercicio_02.view.table.CorrenteTableDefaultRender;
import br.com.contas.exercicio_02.view.table.PoupancaTableDefaultRender;
import br.com.contas.exercicio_02.view.table.CorrenteTableModel;
import br.com.contas.exercicio_02.view.table.PoupancaTableModel;
import br.com.contas.exercicio_02.view.ContaCorrenteIG;
import br.com.contas.exercicio_02.view.ContaPoupancaIG;
import br.com.contas.exercicio_02.view.ContasDepositarDebitarIG;
import br.com.contas.exercicio_02.view.TipoContaIG;
import br.com.contas.exercicio_02.view.TransferenciaEntreContasBancariasIG;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Thiago Tomaz
 */
public class SimuladorDeContasBancariasPrincipalMain extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private CorrenteTableModel correnteTableModel;
    private PoupancaTableModel poupancaTableModel;
    private TableColumnModel modeloColunaPoupanca;
    private TableColumnModel modeloColunasCorrente;
    private final Locale LOCAL_BRASIL = new Locale("pt", "BR");
    private int countPoupanca;
    private int countCorrente;
    private LocalDateTime dataLocal;

    public SimuladorDeContasBancariasPrincipalMain() {

        countPoupanca = 0;
        countCorrente = 0;
        initComponents();
        correnteTableModel = new CorrenteTableModel(LOCAL_BRASIL);
        poupancaTableModel = new PoupancaTableModel(LOCAL_BRASIL);
        setIconImage(Toolkit.getDefaultToolkit().getImage(ICONE_LAUNCH));

        //atribuindo os models as suas respectivas tabelas;
        tabelaContaCorrente.setModel(correnteTableModel);
        tabelaContaPounca.setModel(poupancaTableModel);

        //aqui eu pego o model das colunas para poder manipular o seu tamanho posteriormente
        modeloColunaPoupanca = tabelaContaPounca.getColumnModel();

        // aqui eu manipulo o tamanho das colunas da tabela 
        // ao usar o maxWidth, consigo manipular o tamanho das colunas proporcionalmente;
        modeloColunaPoupanca.getColumn(0).setMaxWidth(50);
        modeloColunaPoupanca.getColumn(1).setMaxWidth(280);
        modeloColunaPoupanca.getColumn(2).setMaxWidth(2100);
        modeloColunaPoupanca.getColumn(3).setMaxWidth(200);
        modeloColunaPoupanca.getColumn(4).setMaxWidth(350);

        //aqui eu pego o model das colunas para poder manipular o seu tamanho posteriormente
        modeloColunasCorrente = tabelaContaCorrente.getColumnModel();

        // aqui eu manipulo o tamanho das colunas da tabela 
        // ao usar o maxWidth, consigo manipular o tamanho das colunas proporcionalmente;
        modeloColunasCorrente.getColumn(0).setMaxWidth(50);
        modeloColunasCorrente.getColumn(1).setMaxWidth(280);
        modeloColunasCorrente.getColumn(2).setMaxWidth(2100);
        modeloColunasCorrente.getColumn(3).setMaxWidth(200);
        modeloColunasCorrente.getColumn(4).setMaxWidth(350);

        //**** obs.: NÃO precisei desativar o AUTO_RESEZI (redimensionamento automatico) das tabelas;
        //configurações da data e hora
        dataLocal = LocalDateTime.now();
        atualizarDataHora(dataLocal);
        startRelogio();

        tabelaContaCorrente.setDefaultRenderer(Object.class, new CorrenteTableDefaultRender());
        tabelaContaPounca.setDefaultRenderer(Object.class, new PoupancaTableDefaultRender());

        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdicionarConta = new javax.swing.JButton();
        btnEditarConta = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DivisorLabel = new javax.swing.JLabel();
        numeroDaConta = new javax.swing.JFormattedTextField();
        lgdContasTipos = new javax.swing.JLabel();
        lgdCountContas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        painelGuiaContas = new javax.swing.JTabbedPane();
        scrollContaPoupanca = new javax.swing.JScrollPane();
        tabelaContaPounca = new javax.swing.JTable();
        scrollContaCorrente = new javax.swing.JScrollPane();
        tabelaContaCorrente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lgdHorario = new javax.swing.JLabel();
        lgdDataHora = new javax.swing.JLabel();
        lgdContaNoVermelho = new javax.swing.JLabel();
        lgdContaNoVermelhoTexto = new javax.swing.JLabel();
        lgdAmarela = new javax.swing.JLabel();
        lgdAmarelaTexto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lgdLaranja = new javax.swing.JLabel();
        lgdaranjaTexto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnPoupanca = new javax.swing.JMenuItem();
        MnContaCorrente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCreditarNaContaPoupanca = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        mnTransferenciaEntreCorrentes = new javax.swing.JMenuItem();
        mnTransferenciaCorrentePoupanca = new javax.swing.JMenuItem();
        mnTransferenciaPoupancaCorrente = new javax.swing.JMenuItem();
        mnTransferenciaEntrePoupancas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistemas de contas Bancarias");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnAdicionarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/add.png"))); // NOI18N
        btnAdicionarConta.setFocusable(false);
        btnAdicionarConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarConta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarContaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdicionarConta);

        btnEditarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/edit.png"))); // NOI18N
        btnEditarConta.setEnabled(false);
        btnEditarConta.setFocusable(false);
        btnEditarConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarConta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditarConta);

        btnExcluirConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/delete.png"))); // NOI18N
        btnExcluirConta.setEnabled(false);
        btnExcluirConta.setFocusable(false);
        btnExcluirConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirConta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirConta);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("l");
        jLabel2.setOpaque(true);
        jToolBar1.add(jLabel2);

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 40));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/seacher.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Número da Conta:");

        DivisorLabel.setBackground(new java.awt.Color(153, 153, 153));
        DivisorLabel.setOpaque(true);

        try {
            numeroDaConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        numeroDaConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lgdContasTipos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lgdContasTipos.setText("Contas poupanças:");

        lgdCountContas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lgdCountContas.setText("0 ");

        jButton1.setText("Limpar seleção");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lgdContasTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdCountContas)
                .addGap(18, 18, 18)
                .addComponent(DivisorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lgdContasTipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdCountContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DivisorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numeroDaConta))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        painelGuiaContas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                painelGuiaContasStateChanged(evt);
            }
        });
        painelGuiaContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelGuiaContasMouseClicked(evt);
            }
        });

        tabelaContaPounca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Numero da Conta", "Nome", "Saldo", "Saldo Poupança"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContaPounca.setRowHeight(28);
        tabelaContaPounca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContaPouncaMouseClicked(evt);
            }
        });
        scrollContaPoupanca.setViewportView(tabelaContaPounca);

        painelGuiaContas.addTab("Lista Conta Poupança", scrollContaPoupanca);

        scrollContaCorrente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollContaCorrenteMouseClicked(evt);
            }
        });

        tabelaContaCorrente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Numero da Conta", "Nome", "Saldo", "Limite Crédito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaContaCorrente.setRowHeight(28);
        tabelaContaCorrente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContaCorrenteMouseClicked(evt);
            }
        });
        scrollContaCorrente.setViewportView(tabelaContaCorrente);

        painelGuiaContas.addTab("Lista Conta Corrente", scrollContaCorrente);

        lgdHorario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lgdHorario.setText("Horário:");

        lgdDataHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lgdDataHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lgdDataHora.setText("21-10-2025");

        lgdContaNoVermelho.setBackground(new java.awt.Color(255, 0, 0));
        lgdContaNoVermelho.setToolTipText("<html><p><b>Conta poupança:</b> Será bloqueado a transferência quando o saldo estiver zerado!</p>\n<p><b>Conta Corrente:</b> Será bloqueado a transfêrencia quando o saldo usar todo o  limite de crédito;</p></html>");
        lgdContaNoVermelho.setOpaque(true);

        lgdContaNoVermelhoTexto.setText("Bloqueada para débito e transferência");

        lgdAmarela.setBackground(new java.awt.Color(255, 255, 0));
        lgdAmarela.setToolTipText("<html><b>Conta Corrente:</b> Legenda ativa quando o saldo for todo utilizado ( 0 ) e começar a utilizar o limite de crédito da conta.</html>");
        lgdAmarela.setOpaque(true);

        lgdAmarelaTexto.setText("Utilizando o limite de crédito da  conta");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Legendas:");

        lgdLaranja.setBackground(java.awt.Color.orange);
        lgdLaranja.setToolTipText("<html><b>Conta Poupança:</b> Legenda ativa quando o saldo da conta poupança estiver zerado.</html>");
        lgdLaranja.setOpaque(true);

        lgdaranjaTexto.setText("Bloqueada para transferência SP->SC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdContaNoVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdContaNoVermelhoTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgdAmarela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdAmarelaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgdLaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdaranjaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lgdHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgdDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lgdContaNoVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgdContaNoVermelhoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdAmarela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdAmarelaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdLaranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdaranjaTexto))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lgdDataHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        MnPoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        MnPoupanca.setText("Contas Poupança");
        MnPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPoupancaActionPerformed(evt);
            }
        });
        jMenu1.add(MnPoupanca);

        MnContaCorrente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        MnContaCorrente.setText("Conta Corrente");
        MnContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnContaCorrenteActionPerformed(evt);
            }
        });
        jMenu1.add(MnContaCorrente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operações das contas");

        mnCreditarNaContaPoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnCreditarNaContaPoupanca.setText("Creditar na Conta Poupança");
        mnCreditarNaContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCreditarNaContaPoupancaActionPerformed(evt);
            }
        });
        jMenu2.add(mnCreditarNaContaPoupanca);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem5.setText("Creditar Em Poupança");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem6.setText("Debitar da Conta Poupança");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem7.setText("Debitar da Poupança");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem8.setText("Creditar na Conta Corrente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem4.setText("Debitar ContaCorrente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transferências");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        mnTransferenciaEntreCorrentes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        mnTransferenciaEntreCorrentes.setText("Tranferência entre Contas correntes");
        mnTransferenciaEntreCorrentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaEntreCorrentesActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaEntreCorrentes);

        mnTransferenciaCorrentePoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnTransferenciaCorrentePoupanca.setText("Transferência de conta Corrente - Poupança");
        mnTransferenciaCorrentePoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaCorrentePoupancaActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaCorrentePoupanca);

        mnTransferenciaPoupancaCorrente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnTransferenciaPoupancaCorrente.setText("Transferência de conta Poupança - Corrente");
        mnTransferenciaPoupancaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaPoupancaCorrenteActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaPoupancaCorrente);

        mnTransferenciaEntrePoupancas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        mnTransferenciaEntrePoupancas.setText("Transferência entre contas Poupanças");
        mnTransferenciaEntrePoupancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaEntrePoupancasActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaEntrePoupancas);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelGuiaContas)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelGuiaContas, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPoupancaActionPerformed
        contaPoupancaGUI(null, true);

    }//GEN-LAST:event_MnPoupancaActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void MnContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnContaCorrenteActionPerformed
        contaCorrenteGUI(null, true);

    }//GEN-LAST:event_MnContaCorrenteActionPerformed

    private void mnCreditarNaContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCreditarNaContaPoupancaActionPerformed

        if (tabelaContaPounca.getRowCount() > 0) {
            ContasDepositarDebitarIG operacoesContaPoupanca = new ContasDepositarDebitarIG(ICONE_LAUNCH, true, 1);
            operacoesContaPoupanca.setModal(true);
            operacoesContaPoupanca.setVisible(true);

            String numerodaconta = operacoesContaPoupanca.getNumeroDaConta();
            double valorDeposito = operacoesContaPoupanca.getValorCreditado();

            if (numerodaconta != null && valorDeposito != 0) {
                ContaPoupanca cp = poupancaTableModel.getContaPoupanca(numerodaconta);
                if (cp != null) {
                    operacoesBancarias.creditarContaPoupanca(cp, valorDeposito);
                    poupancaTableModel.updateContaCorrente(cp);

                } else {
                    JOptionPane.showMessageDialog(this, "Deposito não efetuado, numero da conta poupança inexistente\nTente Novamente!!!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma conta poupança cadastrada! ");
        }
        limparSelecaoTabelas();
    }//GEN-LAST:event_mnCreditarNaContaPoupancaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        if (tabelaContaPounca.getRowCount() > 0) {

            ContasDepositarDebitarIG operacoesContaPoupanca = new ContasDepositarDebitarIG(ICONE_LAUNCH, true, 2);
            operacoesContaPoupanca.setModal(true);
            operacoesContaPoupanca.setVisible(true);

            String numerodaconta = operacoesContaPoupanca.getNumeroDaConta();
            double valorDeposito = operacoesContaPoupanca.getValorCreditado();

            if (numerodaconta != null && valorDeposito != 0) {
                ContaPoupanca cp = poupancaTableModel.getContaPoupanca(numerodaconta);
                if (cp != null) {

                    operacoesBancarias.creditarEmPoupanca(cp, valorDeposito);
                    poupancaTableModel.updateContaCorrente(cp);

                } else {
                    JOptionPane.showMessageDialog(this, "Deposito não efetuado, numero da conta poupança inexistente\nTente Novamente!!!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma conta poupança cadastrada! ");
        }

        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (tabelaContaPounca.getRowCount() > 0) {

            ContasDepositarDebitarIG operacoesContaPoupanca = new ContasDepositarDebitarIG(ICONE_LAUNCH, true, 3);
            operacoesContaPoupanca.setModal(true);
            operacoesContaPoupanca.setVisible(true);

            String numerodaconta = operacoesContaPoupanca.getNumeroDaConta();
            double valorDeposito = operacoesContaPoupanca.getValorCreditado();

            if (numerodaconta != null && valorDeposito != 0) {
                ContaPoupanca cp = poupancaTableModel.getContaPoupanca(numerodaconta);
                if (cp != null) {
                    operacoesBancarias.debitarContaPoupanca(cp, valorDeposito);
                    poupancaTableModel.updateContaCorrente(cp);
                } else {
                    JOptionPane.showMessageDialog(this, "Deposito não efetuado, numero da conta poupança inexistente\nTente Novamente!!!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma conta poupança cadastrada! ");
        }

        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (tabelaContaPounca.getRowCount() > 0) {

            ContasDepositarDebitarIG operacoesContaPoupanca = new ContasDepositarDebitarIG(ICONE_LAUNCH, true, 4);
            operacoesContaPoupanca.setModal(true);
            operacoesContaPoupanca.setVisible(true);

            String numerodaconta = operacoesContaPoupanca.getNumeroDaConta();
            double valorDeposito = operacoesContaPoupanca.getValorCreditado();

            if (numerodaconta != null && valorDeposito != 0) {
                ContaPoupanca cp = poupancaTableModel.getContaPoupanca(numerodaconta);
                if (cp != null) {
                    operacoesBancarias.debitarDaPoupanca(cp, valorDeposito);
                    poupancaTableModel.updateContaCorrente(cp);
                } else {
                    JOptionPane.showMessageDialog(this, "Deposito não efetuado, numero da conta poupança inexistente\nTente Novamente!!!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma conta poupança cadastrada! ");
        }
        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (tabelaContaCorrente.getRowCount() > 0) {

            ContasDepositarDebitarIG operacoesContas = new ContasDepositarDebitarIG(ICONE_LAUNCH, true, 6);
            operacoesContas.setModal(true);
            operacoesContas.setVisible(true);

            String numerodaconta = operacoesContas.getNumeroDaConta();
            double valorDeposito = operacoesContas.getValorCreditado();

            if (numerodaconta != null && valorDeposito != 0) {
                ContaCorrente cc = correnteTableModel.getContaCorrente(numerodaconta);
                if (cc != null) {

                    operacoesBancarias.debitarContaCorrente(cc, valorDeposito);
                    correnteTableModel.updateContaCorrente(cc);
                } else {
                    JOptionPane.showMessageDialog(this, "Deposito não efetuado, numero da conta corrente inexistente\nTente Novamente!!!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma conta corrente cadastrada! ");
        }
        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (tabelaContaCorrente.getRowCount() > 0) {

            ContasDepositarDebitarIG operacoesContaPoupanca = new ContasDepositarDebitarIG(ICONE_LAUNCH, true, 5);
            operacoesContaPoupanca.setModal(true);
            operacoesContaPoupanca.setVisible(true);

            String numerodaconta = operacoesContaPoupanca.getNumeroDaConta();
            double valorDeposito = operacoesContaPoupanca.getValorCreditado();

            if (numerodaconta != null && valorDeposito != 0) {
                ContaCorrente cc = correnteTableModel.getContaCorrente(numerodaconta);
                if (cc != null) {
                    operacoesBancarias.creditarContaCorrente(cc, valorDeposito);
                    correnteTableModel.updateContaCorrente(cc);
                } else {
                    JOptionPane.showMessageDialog(this, "Deposito não efetuado, numero da conta corrente inexistente\nTente Novamente!!!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma conta corrente cadastrada! ");
        }
        limparSelecaoTabelas();
            }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mnTransferenciaEntreCorrentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaEntreCorrentesActionPerformed

        if (tabelaContaCorrente.getRowCount() > 1) {

            TransferenciaEntreContasBancariasIG transferenciaEntreContasCorrentes = new TransferenciaEntreContasBancariasIG(this, true, ICONE_LAUNCH, 1);
            transferenciaEntreContasCorrentes.setVisible(true);

            String numeroContaOrigem = transferenciaEntreContasCorrentes.getNumeroContaOrigem();
            String numeroContaDestino = transferenciaEntreContasCorrentes.getNumeroContaDestino();
            double valorDeposito = transferenciaEntreContasCorrentes.getValorTransferencia();

            if (numeroContaOrigem != null && valorDeposito != 0 && numeroContaDestino != null) {
                ContaCorrente ccOrigem = correnteTableModel.getContaCorrente(numeroContaOrigem);
                ContaCorrente ccDestino = correnteTableModel.getContaCorrente(numeroContaDestino);

                if (ccOrigem != null) {
                    if (ccDestino != null) {
                        operacoesBancarias.transferenciaBancaria(ccOrigem, ccDestino, valorDeposito);
                        correnteTableModel.updateContaCorrente(ccOrigem);
                        correnteTableModel.updateContaCorrente(ccDestino);
                    } else {
                        JOptionPane.showMessageDialog(this, "Conta de destino inexistente\nTente Novamente!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Conta de origem inexistente\nTente Novamente!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Transferência indisponivel no momento!\n\nPara realizar essa operação é necessário\nter pelo menos 2 contas distintas cadastradas!\n[ " + countCorrente + " ] conta correntes.");
        }
        limparSelecaoTabelas();

    }//GEN-LAST:event_mnTransferenciaEntreCorrentesActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized


    }//GEN-LAST:event_formComponentResized

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void btnAdicionarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarContaActionPerformed
        TipoContaIG tipoContaGUI = new TipoContaIG(ICONE_LAUNCH);
        tipoContaGUI.setModal(true);
        tipoContaGUI.setVisible(true);
        int tipoConta = tipoContaGUI.getTipoConta();

        if (!(tipoConta < 0)) {
           
            if (tipoConta == 0) {
                contaPoupancaGUI(null, true);
            } else if (tipoConta == 1) {
                contaCorrenteGUI(null, true);
            }

        }


    }//GEN-LAST:event_btnAdicionarContaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (painelGuiaContas.getSelectedIndex() == 0) {
            if (tabelaContaPounca.getRowCount() > 0) {
                if (poupancaTableModel.getContaPoupanca(numeroDaConta.getText().trim()) != null) {
                    JOptionPane.showMessageDialog(this, "O número da conta poupança: [" + numeroDaConta.getText().trim() + " ] é válido!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Número de conta inexistente!");

            }

        } else {
            if (tabelaContaCorrente.getRowCount() > 0) {
                ContaCorrente cc = correnteTableModel.getContaCorrente(numeroDaConta.getText().trim());
                if (cc != null) {
                    JOptionPane.showMessageDialog(this, "O número da conta corrente: [" + numeroDaConta.getText().trim() + " ] é válido!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Número de conta inexistente!");

            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void painelGuiaContasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_painelGuiaContasStateChanged
        limparSelecaoTabelas();
        atualizarCountContas(0);

    }//GEN-LAST:event_painelGuiaContasStateChanged

    private void scrollContaCorrenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollContaCorrenteMouseClicked

    }//GEN-LAST:event_scrollContaCorrenteMouseClicked

    private void tabelaContaCorrenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContaCorrenteMouseClicked
        btnEditarConta.setEnabled(true);
        btnExcluirConta.setEnabled(true);

    }//GEN-LAST:event_tabelaContaCorrenteMouseClicked

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        deletarContas();

    }//GEN-LAST:event_btnExcluirContaActionPerformed

    private void btnEditarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContaActionPerformed
        if (painelGuiaContas.getSelectedIndex() == 0) {
            int linha = tabelaContaPounca.getSelectedRow();
            if (linha > -1) {
                ContaPoupanca cp = poupancaTableModel.getContaPoupanca(linha);
                contaPoupancaGUI(cp, false);
            }
        } else {
            int linha = tabelaContaCorrente.getSelectedRow();
            if (linha > -1) {
                ContaCorrente cc = correnteTableModel.getContaCorrente(linha);
                contaCorrenteGUI(cc, false);
            }
        }
    }//GEN-LAST:event_btnEditarContaActionPerformed

    private void tabelaContaPouncaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContaPouncaMouseClicked
        btnEditarConta.setEnabled(true);
        btnExcluirConta.setEnabled(true);
    }//GEN-LAST:event_tabelaContaPouncaMouseClicked

    private void painelGuiaContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelGuiaContasMouseClicked

    }//GEN-LAST:event_painelGuiaContasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limparSelecaoTabelas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mnTransferenciaCorrentePoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaCorrentePoupancaActionPerformed

        if (countCorrente > 0 && countPoupanca > 0) {
            TransferenciaEntreContasBancariasIG tcp = new TransferenciaEntreContasBancariasIG(this, true, ICONE_LAUNCH, 2);
            tcp.setVisible(true);

            String numeroContaOrigem = tcp.getNumeroContaOrigem();
            String numeroContaDestino = tcp.getNumeroContaDestino();
            double valorDeposito = tcp.getValorTransferencia();

            if (numeroContaOrigem != null && valorDeposito != 0 && numeroContaDestino != null) {
                ContaCorrente ccOrigem = correnteTableModel.getContaCorrente(numeroContaOrigem);
                ContaPoupanca cpDestino = poupancaTableModel.getContaPoupanca(numeroContaDestino);

                if (ccOrigem != null) {
                    if (cpDestino != null) {

                        operacoesBancarias.transferenciaCorrenteParaPoupanca(ccOrigem, cpDestino, valorDeposito);
                        correnteTableModel.updateContaCorrente(ccOrigem);
                        poupancaTableModel.updateContaCorrente(cpDestino);
                    } else {
                        JOptionPane.showMessageDialog(this, "Conta de destino inexistente\nTente Novamente!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Conta de origem inexistente\nTente Novamente!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Transferência indisponivel no momento!\n\nPara realizar essa operação é necessário\nter pelo menos 2 contas distintas cadastradas!\n[ " + countPoupanca + " ] conta poupança;\n[ " + countCorrente + " ] conta corrente.");
        }
    }//GEN-LAST:event_mnTransferenciaCorrentePoupancaActionPerformed

    private void mnTransferenciaPoupancaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaPoupancaCorrenteActionPerformed

        if (countPoupanca > 0 && countCorrente > 0) {
            TransferenciaEntreContasBancariasIG tpc = new TransferenciaEntreContasBancariasIG(this, true, ICONE_LAUNCH, 3);
            tpc.setVisible(true);

            String numeroContaOrigem = tpc.getNumeroContaOrigem();
            String numeroContaDestino = tpc.getNumeroContaDestino();
            double valorDeposito = tpc.getValorTransferencia();

            if (numeroContaOrigem != null && valorDeposito != 0 && numeroContaDestino != null) {
                ContaPoupanca cpOrigem = poupancaTableModel.getContaPoupanca(numeroContaOrigem);
                ContaCorrente ccDestino = correnteTableModel.getContaCorrente(numeroContaDestino);

                if (cpOrigem != null) {
                    if (ccDestino != null) {
                        operacoesBancarias.transferenciaPoupancaParaCorrente(cpOrigem, ccDestino, valorDeposito);
                        poupancaTableModel.updateContaCorrente(cpOrigem);
                        correnteTableModel.updateContaCorrente(ccDestino);
                    } else {
                        JOptionPane.showMessageDialog(this, "Conta de destino inexistente\nTente Novamente!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Conta de origem inexistente\nTente Novamente!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Transferência indisponivel no momento!\n\nPara realizar essa operação é necessário\nter pelo menos 2 contas distintas cadastradas!\n[ " + countCorrente + " ] conta corrente;\n[ " + countPoupanca + " ] conta poupança.");
        }
    }//GEN-LAST:event_mnTransferenciaPoupancaCorrenteActionPerformed

    private void mnTransferenciaEntrePoupancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaEntrePoupancasActionPerformed
        if (countPoupanca > 1) {
            TransferenciaEntreContasBancariasIG tpp = new TransferenciaEntreContasBancariasIG(this, true, ICONE_LAUNCH, 4);
            tpp.setVisible(true);

            String numeroContaOrigem = tpp.getNumeroContaOrigem();
            String numeroContaDestino = tpp.getNumeroContaDestino();
            double valorDeposito = tpp.getValorTransferencia();

            if (numeroContaOrigem != null && valorDeposito != 0 && numeroContaDestino != null) {

                ContaPoupanca cpOrigem = poupancaTableModel.getContaPoupanca(numeroContaOrigem);
                ContaPoupanca cpDestino = poupancaTableModel.getContaPoupanca(numeroContaDestino);
               
                if (cpOrigem!=null) {
                    if (cpDestino!=null) {
                        operacoesBancarias.transferenciaPoupancaParaPoupanca(cpOrigem, cpDestino, valorDeposito);
                        poupancaTableModel.updateContaCorrente(cpOrigem);
                        poupancaTableModel.updateContaCorrente(cpDestino);
                        System.out.println("Nome: " + cpOrigem.getNome() + " | " + cpOrigem.getSaldo() + " | " + cpDestino.getNome() + " | " + cpDestino.getSaldo());
                    } else {
                        JOptionPane.showMessageDialog(this, "Conta de destino inexistente\nTente Novamente!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Conta de origem inexistente\nTente Novamente!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Transferência indisponivel no momento!\n\nPara realizar essa operação é necessário\nter pelo menos 2 contas poupanças cadastradas!\n[ " + countPoupanca + " ] conta poupança;");
        }
    }//GEN-LAST:event_mnTransferenciaEntrePoupancasActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorDeContasBancariasPrincipalMain().setVisible(true);
            }
        });
    }

    private ContaPoupanca contaPoupanca = null;
    private ContaCorrente contaCorrente = null;
    private OperacoesBancarias operacoesBancarias = new OperacoesBancarias();
    private final String ICONE_LAUNCH = "resources\\icone_launcher\\bank_2.png";


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DivisorLabel;
    private javax.swing.JMenuItem MnContaCorrente;
    private javax.swing.JMenuItem MnPoupanca;
    private javax.swing.JButton btnAdicionarConta;
    private javax.swing.JButton btnEditarConta;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lgdAmarela;
    private javax.swing.JLabel lgdAmarelaTexto;
    private javax.swing.JLabel lgdContaNoVermelho;
    private javax.swing.JLabel lgdContaNoVermelhoTexto;
    private javax.swing.JLabel lgdContasTipos;
    private javax.swing.JLabel lgdCountContas;
    private javax.swing.JLabel lgdDataHora;
    private javax.swing.JLabel lgdHorario;
    private javax.swing.JLabel lgdLaranja;
    private javax.swing.JLabel lgdaranjaTexto;
    private javax.swing.JMenuItem mnCreditarNaContaPoupanca;
    private javax.swing.JMenuItem mnTransferenciaCorrentePoupanca;
    private javax.swing.JMenuItem mnTransferenciaEntreCorrentes;
    private javax.swing.JMenuItem mnTransferenciaEntrePoupancas;
    private javax.swing.JMenuItem mnTransferenciaPoupancaCorrente;
    private javax.swing.JFormattedTextField numeroDaConta;
    private javax.swing.JTabbedPane painelGuiaContas;
    private javax.swing.JScrollPane scrollContaCorrente;
    private javax.swing.JScrollPane scrollContaPoupanca;
    private javax.swing.JTable tabelaContaCorrente;
    private javax.swing.JTable tabelaContaPounca;
    // End of variables declaration//GEN-END:variables

    private boolean isContaPoupancaPreenchida() {
        return contaPoupanca != null;
    }

    private boolean isContaCorrentePreenchida() {
        return contaCorrente != null;
    }

    private void contaCorrenteGUI(ContaCorrente contaCorrente, boolean cadastro) {
         painelGuiaContas.setSelectedIndex(1);
         
        ContaCorrenteIG guicc = new ContaCorrenteIG(ICONE_LAUNCH, LOCAL_BRASIL);
        guicc.setContaCorrente(contaCorrente);
        guicc.setModal(true);
        guicc.setVisible(true);
        contaCorrente = guicc.getContaCorrente();

        if (contaCorrente != null) {
            if (cadastro) {

                if (correnteTableModel.getContaCorrente(contaCorrente.getNumeroConta().trim()) == null) {
                    correnteTableModel.addRow(contaCorrente);
                    atualizarCountContas(1);
                    JOptionPane.showMessageDialog(this, "Parabéns " + contaCorrente.getNome() + "\nSua conta Corrente foi criada com sucesso\n");
                } else {
                    JOptionPane.showMessageDialog(this, "Prezado, " + contaCorrente.getNome() + " o número da conta já pertence a outra correntista,\n\nTente Novamente\n");
                }
            } else {

                correnteTableModel.updateContaCorrente(contaCorrente);
            }

        }
        limparSelecaoTabelas();
    }

    private void contaPoupancaGUI(ContaPoupanca contaPoupanca, boolean cadastro) {
        
         painelGuiaContas.setSelectedIndex(0);
        ContaPoupancaIG guiP = new ContaPoupancaIG(ICONE_LAUNCH, LOCAL_BRASIL);
        guiP.setContaPoupanca(contaPoupanca);
        guiP.setModal(true);
        guiP.setVisible(true);

        contaPoupanca = guiP.getContaPoupanca();

        if (contaPoupanca != null) {
            if (cadastro) {
                if (poupancaTableModel.getContaPoupanca(contaPoupanca.getNumeroConta().trim())==null) {
                    poupancaTableModel.addRow(contaPoupanca);
                    atualizarCountContas(1);
                    JOptionPane.showMessageDialog(this, "Parabéns " + contaPoupanca.getNome() + "\nSua conta poupança foi criada com sucesso\n");

                } else {
                    JOptionPane.showMessageDialog(this, "Prezado, " + contaPoupanca.getNome() + " o número da conta já pertence a outra pessoa,\n\nTente Novamente\n");
                }
            } else {
                poupancaTableModel.updateContaCorrente(contaPoupanca);
            }

        }
        limparSelecaoTabelas();
    }

    private void limparSelecaoTabelas() {
        if (painelGuiaContas.getSelectedIndex() == 0) {
            tabelaContaPounca.clearSelection();
        } else {
            tabelaContaCorrente.clearSelection();
        }

        btnEditarConta.setEnabled(false);
        btnExcluirConta.setEnabled(false);
    }

    private void deletarContas() {
        if (painelGuiaContas.getSelectedIndex() == 0) {
            int linha = tabelaContaPounca.getSelectedRow();
            if (linha > -1) {

                ContaPoupanca cp = poupancaTableModel.getContaPoupanca(linha);

                int opcao = JOptionPane.showConfirmDialog(this, cp.getNome() + ", deseja realmente exluir sua conta poupança?\n\nNúmero da conta: [ " + cp.getNumeroConta() + " ]", "Confirmar remoção de conta", JOptionPane.YES_NO_OPTION);
                if (opcao == JOptionPane.YES_OPTION) {
                    poupancaTableModel.deleteContaPoupanca(linha);
                    atualizarCountContas(-1);
                }

            }

        } else {
            int linhaTabelaContaCorrente = tabelaContaCorrente.getSelectedRow();
            if (linhaTabelaContaCorrente > -1) {

                ContaCorrente cp = correnteTableModel.getContaCorrente(linhaTabelaContaCorrente);

                int opcao = JOptionPane.showConfirmDialog(this, cp.getNome() + ", deseja realmente exluir sua conta corrente?\n\nNúmero da conta: [ " + cp.getNumeroConta() + " ]", "Confirmar remoção de conta", JOptionPane.YES_NO_OPTION);
                if (opcao == JOptionPane.YES_OPTION) {
                    correnteTableModel.deleteContaCorrente(linhaTabelaContaCorrente);
                    atualizarCountContas(-1);
                }
            }
        }
    }

    private void atualizarCountContas(int incrementoDecremento) {
        if (painelGuiaContas.getSelectedIndex() == 0) {
            lgdContasTipos.setText("Contas poupanças: ");
            // aqui tem que tomar cuidado, pois no contrutor o componente tabbepane é criando antes de se instanciar a classe poupancaTableModel e correntTableModel
            countPoupanca += incrementoDecremento;
            lgdCountContas.setText(countPoupanca + "");
        } else {
            lgdContasTipos.setText("Contas correntes: ");
            // aqui tem que tomar cuidado, pois no contrutor o componente tabbepane é criando antes de se instanciar a classe poupancaTableModel e correntTableModel
            countCorrente += incrementoDecremento;
            lgdCountContas.setText(countCorrente + "");
        }
    }

    private void atualizarDataHora(LocalDateTime dataLocal) {
        lgdDataHora.setText(dataLocal.format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")));
    }

    private void startRelogio() {
        Timer relogio = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dataLocal = dataLocal.plusSeconds(1);
                atualizarDataHora(dataLocal);
            }
        });

        relogio.start();
    }

}
