/*
 *Componentes:
*   Emanuel Basílio da Silva (20251134040033) 
    Matheus do Nascimento da Silva (20251134040023)
    RENATO ARAUJO GRILO (20251134040018)
    Thiago Tomaz de Araújo (20251134040031)
 */
package br.com.contas.exercicio_02.main;

import br.com.contas.exercicio_02.controller.ContasBancariasController;
import br.com.contas.exercicio_02.model.classes.EnumTipoConta;
import br.com.contas.exercicio_02.model.enums.EnumValidacaoCampos;
import br.com.contas.exercicio_02.model.exception.NuloVazioInesxistenteException;
import br.com.contas.exercicio_02.services.ContaBancariaServices;
import br.com.contas.exercicio_02.services.OperacoesBancariasServices;
import br.com.contas.exercicio_02.model.util.ConfigDefaultSistema;
import br.com.contas.exercicio_02.model.util.Mensagens;
import br.com.contas.exercicio_02.model.util.ValidarValores;
import br.com.contas.exercicio_02.view.EnumAcaoView;
import br.com.contas.exercicio_02.view.table.ContaBancariaTableModel;
import br.com.contas.exercicio_02.view.TipoContaIG;
import br.com.contas.exercicio_02.model.classes.EnumTipoOperacoes;
import br.com.contas.exercicio_02.view.table.CacheContas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.Timer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Thiago Tomaz
 */
public class SimuladorDeContasBancariasPrincipalMain extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ContasBancariasController contasBancariasController;

    private TableColumnModel contaBancariaModelColumn;

    private int countPoupanca;
    private int countCorrente;
    private LocalDateTime dataLocal;

    public SimuladorDeContasBancariasPrincipalMain() {

        countPoupanca = 0;
        countCorrente = 0;
        initComponents();

        setIconImage(ConfigDefaultSistema.getICONE_SISTEMA());

        //instanciando os objeto controlle
        contasBancariasController = new ContasBancariasController(this);

        //atribuindo os models as suas respectivas tabelas;
        tabelaContabancaria.setModel(contasBancariasController.getContaBancariaModeloTable());

        //aqui eu pego o model das colunas para poder manipular o seu tamanho posteriormente
        contaBancariaModelColumn = tabelaContabancaria.getColumnModel();

        // aqui eu manipulo o tamanho das colunas da tabela 
        // ao usar o maxWidth, consigo manipular o tamanho das colunas proporcionalmente;
        contaBancariaModelColumn.getColumn(0).setMaxWidth(50);
        contaBancariaModelColumn.getColumn(1).setMaxWidth(280);
        contaBancariaModelColumn.getColumn(2).setMaxWidth(2100);
        contaBancariaModelColumn.getColumn(3).setMaxWidth(200);
        contaBancariaModelColumn.getColumn(4).setMaxWidth(350);
        contaBancariaModelColumn.getColumn(5).setMaxWidth(600);

        //aqui eu pego o model das colunas para poder manipular o seu tamanho posteriormente
        //**** obs.: NÃO precisei desativar o AUTO_RESEZI (redimensionamento automatico) das tabelas;
        //configurações da data e hora
        dataLocal = LocalDateTime.now();
        atualizarDataHora(dataLocal);
        startRelogio();
        
        //Interligando o enum com o JCombobox
         cbxTiposContas.setModel(new DefaultComboBoxModel<>(EnumTipoConta.values()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdicionarConta = new javax.swing.JButton();
        btnEditarConta = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DivisorLabel = new javax.swing.JLabel();
        txtNumeroDaConta = new javax.swing.JFormattedTextField();
        lgdContasTipos = new javax.swing.JLabel();
        lgdCountContas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbxTiposContas = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lgdHorario = new javax.swing.JLabel();
        lgdDataHora = new javax.swing.JLabel();
        lgdContaNoVermelho = new javax.swing.JLabel();
        lgdContaNoVermelhoTexto = new javax.swing.JLabel();
        lgdAmarela = new javax.swing.JLabel();
        lgdAmarelaTexto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lgdLaranja = new javax.swing.JLabel();
        lgdaranjaTexto = new javax.swing.JLabel();
        painelContasBancarias = new javax.swing.JPanel();
        scrollContaPoupanca = new javax.swing.JScrollPane();
        tabelaContabancaria = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnPoupanca = new javax.swing.JMenuItem();
        MnContaCorrente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCreditarNaContaPoupanca = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        mnTransferenciaEntreCorrentes = new javax.swing.JMenuItem();
        mnTransferenciaCorrentePoupanca = new javax.swing.JMenuItem();
        mnTransferenciaPoupancaCorrente = new javax.swing.JMenuItem();
        mnTransferenciaEntrePoupancas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistemas de contas Bancarias");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnAdicionarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/add.png"))); // NOI18N
        btnAdicionarConta.setFocusable(false);
        btnAdicionarConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarConta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarContaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdicionarConta);

        btnEditarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/edit.png"))); // NOI18N
        btnEditarConta.setEnabled(false);
        btnEditarConta.setFocusable(false);
        btnEditarConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarConta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditarConta);

        btnExcluirConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/delete.png"))); // NOI18N
        btnExcluirConta.setEnabled(false);
        btnExcluirConta.setFocusable(false);
        btnExcluirConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirConta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirConta);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("l");
        jLabel2.setOpaque(true);
        jToolBar1.add(jLabel2);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/history.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 40));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/seacher.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número da Conta:");

        DivisorLabel.setBackground(new java.awt.Color(153, 153, 153));
        DivisorLabel.setOpaque(true);

        try {
            txtNumeroDaConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroDaConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lgdContasTipos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lgdContasTipos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lgdContasTipos.setText("Contas bancárias:");

        lgdCountContas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lgdCountContas.setText("0 ");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Limpar seleção");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxTiposContas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxTiposContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTiposContasActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(200, 200, 200));
        jLabel4.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tipo Conta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lgdContasTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdCountContas)
                .addGap(18, 18, 18)
                .addComponent(DivisorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTiposContas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lgdContasTipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdCountContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxTiposContas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(DivisorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumeroDaConta))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lgdHorario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lgdHorario.setText("Horário:");

        lgdDataHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lgdDataHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lgdDataHora.setText("21-10-2025");

        lgdContaNoVermelho.setBackground(new java.awt.Color(255, 0, 0));
        lgdContaNoVermelho.setToolTipText("<html><p><b>Conta poupança:</b> Será bloqueado a transferência quando o saldo estiver zerado!</p>\n<p><b>Conta Corrente:</b> Será bloqueado a transfêrencia quando o saldo usar todo o  limite de crédito;</p></html>");
        lgdContaNoVermelho.setOpaque(true);

        lgdContaNoVermelhoTexto.setText("Bloqueada para débito e transferência");

        lgdAmarela.setBackground(new java.awt.Color(255, 255, 0));
        lgdAmarela.setToolTipText("<html><b>Conta Corrente:</b> Legenda ativa quando o saldo for todo utilizado ( 0 ) e começar a utilizar o limite de crédito da conta.</html>");
        lgdAmarela.setOpaque(true);

        lgdAmarelaTexto.setText("Utilizando o limite de crédito da  conta");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Legendas:");

        lgdLaranja.setBackground(java.awt.Color.orange);
        lgdLaranja.setToolTipText("<html><b>Conta Poupança:</b> Legenda ativa quando o saldo da conta poupança estiver zerado.</html>");
        lgdLaranja.setOpaque(true);

        lgdaranjaTexto.setText("Bloqueada para transferência SP->SC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdContaNoVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdContaNoVermelhoTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgdAmarela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdAmarelaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgdLaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgdaranjaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(lgdHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgdDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lgdContaNoVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgdContaNoVermelhoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdAmarela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdAmarelaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdLaranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdaranjaTexto))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lgdDataHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgdHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabelaContabancaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Numero da Conta", "Nome", "Saldo", "Saldo Poupança"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContabancaria.setRowHeight(28);
        tabelaContabancaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContabancariaMouseClicked(evt);
            }
        });
        scrollContaPoupanca.setViewportView(tabelaContabancaria);

        javax.swing.GroupLayout painelContasBancariasLayout = new javax.swing.GroupLayout(painelContasBancarias);
        painelContasBancarias.setLayout(painelContasBancariasLayout);
        painelContasBancariasLayout.setHorizontalGroup(
            painelContasBancariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollContaPoupanca)
        );
        painelContasBancariasLayout.setVerticalGroup(
            painelContasBancariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollContaPoupanca, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        MnPoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        MnPoupanca.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        MnPoupanca.setText("Contas Poupança");
        MnPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPoupancaActionPerformed(evt);
            }
        });
        jMenu1.add(MnPoupanca);

        MnContaCorrente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        MnContaCorrente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        MnContaCorrente.setText("Conta Corrente");
        MnContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnContaCorrenteActionPerformed(evt);
            }
        });
        jMenu1.add(MnContaCorrente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operações das contas");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        mnCreditarNaContaPoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnCreditarNaContaPoupanca.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        mnCreditarNaContaPoupanca.setText("Creditar na Conta Poupança");
        mnCreditarNaContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCreditarNaContaPoupancaActionPerformed(evt);
            }
        });
        jMenu2.add(mnCreditarNaContaPoupanca);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem5.setText("Creditar Em Poupança");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem6.setText("Debitar da Conta Poupança");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem7.setText("Debitar da Poupança");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem8.setText("Creditar na Conta Corrente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem4.setText("Debitar ContaCorrente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transferências");
        jMenu3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        mnTransferenciaEntreCorrentes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        mnTransferenciaEntreCorrentes.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        mnTransferenciaEntreCorrentes.setText("Tranferência entre Contas correntes");
        mnTransferenciaEntreCorrentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaEntreCorrentesActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaEntreCorrentes);

        mnTransferenciaCorrentePoupanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnTransferenciaCorrentePoupanca.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        mnTransferenciaCorrentePoupanca.setText("Transferência de conta Corrente - Poupança");
        mnTransferenciaCorrentePoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaCorrentePoupancaActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaCorrentePoupanca);

        mnTransferenciaPoupancaCorrente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnTransferenciaPoupancaCorrente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        mnTransferenciaPoupancaCorrente.setText("Transferência de conta Poupança - Corrente");
        mnTransferenciaPoupancaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaPoupancaCorrenteActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaPoupancaCorrente);

        mnTransferenciaEntrePoupancas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        mnTransferenciaEntrePoupancas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        mnTransferenciaEntrePoupancas.setText("Transferência entre contas Poupanças");
        mnTransferenciaEntrePoupancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransferenciaEntrePoupancasActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransferenciaEntrePoupancas);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(painelContasBancarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelContasBancarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPoupancaActionPerformed


    }//GEN-LAST:event_MnPoupancaActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void MnContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnContaCorrenteActionPerformed

    }//GEN-LAST:event_MnContaCorrenteActionPerformed

    private void mnCreditarNaContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCreditarNaContaPoupancaActionPerformed

        limparSelecaoTabelas();
    }//GEN-LAST:event_mnCreditarNaContaPoupancaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        limparSelecaoTabelas();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        contasBancariasController.abrirViewRealizarOperacoesDebitoCredito(EnumTipoOperacoes.CREDITAR, jMenuItem8.getText());
        limparSelecaoTabelas();
            }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mnTransferenciaEntreCorrentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaEntreCorrentesActionPerformed

        limparSelecaoTabelas();

    }//GEN-LAST:event_mnTransferenciaEntreCorrentesActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized


    }//GEN-LAST:event_formComponentResized

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void btnAdicionarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarContaActionPerformed

        TipoContaIG tipoContaGUI = new TipoContaIG();
        tipoContaGUI.setModal(true);
        tipoContaGUI.setVisible(true);

        //A interface grafica não decide nada, apenas exibe e executa;
        contasBancariasController.efetuarNovaContaView(tipoContaGUI.getContaView());

        // contaBancariaModeloTable.atualizarTabela();
    }//GEN-LAST:event_btnAdicionarContaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        contasBancariasController.consultarContaBancariaNumeroDaContaViewPrincipal(txtNumeroDaConta.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
       contasBancariasController.excluirContaBancaria(tabelaContabancaria.getSelectedRow());

    }//GEN-LAST:event_btnExcluirContaActionPerformed

    private void btnEditarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContaActionPerformed
       
        contasBancariasController.editarContaBancariaView(EnumAcaoView.EDITAR, tabelaContabancaria.getSelectedRow());
        
    }//GEN-LAST:event_btnEditarContaActionPerformed

    private void tabelaContabancariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContabancariaMouseClicked
        btnEditarConta.setEnabled(true);
        btnExcluirConta.setEnabled(true);
    }//GEN-LAST:event_tabelaContabancariaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limparSelecaoTabelas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mnTransferenciaCorrentePoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaCorrentePoupancaActionPerformed


    }//GEN-LAST:event_mnTransferenciaCorrentePoupancaActionPerformed

    private void mnTransferenciaPoupancaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaPoupancaCorrenteActionPerformed


    }//GEN-LAST:event_mnTransferenciaPoupancaCorrenteActionPerformed

    private void mnTransferenciaEntrePoupancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransferenciaEntrePoupancasActionPerformed

    }//GEN-LAST:event_mnTransferenciaEntrePoupancasActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void cbxTiposContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTiposContasActionPerformed
        contasBancariasController.FiltrarConta((EnumTipoConta) cbxTiposContas.getSelectedItem());
    }//GEN-LAST:event_cbxTiposContasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      contasBancariasController.abrirOperacoesBancariasView();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorDeContasBancariasPrincipalMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorDeContasBancariasPrincipalMain().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DivisorLabel;
    private javax.swing.JMenuItem MnContaCorrente;
    private javax.swing.JMenuItem MnPoupanca;
    private javax.swing.JButton btnAdicionarConta;
    private javax.swing.JButton btnEditarConta;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxTiposContas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lgdAmarela;
    private javax.swing.JLabel lgdAmarelaTexto;
    private javax.swing.JLabel lgdContaNoVermelho;
    private javax.swing.JLabel lgdContaNoVermelhoTexto;
    private javax.swing.JLabel lgdContasTipos;
    private javax.swing.JLabel lgdCountContas;
    private javax.swing.JLabel lgdDataHora;
    private javax.swing.JLabel lgdHorario;
    private javax.swing.JLabel lgdLaranja;
    private javax.swing.JLabel lgdaranjaTexto;
    private javax.swing.JMenuItem mnCreditarNaContaPoupanca;
    private javax.swing.JMenuItem mnTransferenciaCorrentePoupanca;
    private javax.swing.JMenuItem mnTransferenciaEntreCorrentes;
    private javax.swing.JMenuItem mnTransferenciaEntrePoupancas;
    private javax.swing.JMenuItem mnTransferenciaPoupancaCorrente;
    private javax.swing.JPanel painelContasBancarias;
    private javax.swing.JScrollPane scrollContaPoupanca;
    private javax.swing.JTable tabelaContabancaria;
    private javax.swing.JFormattedTextField txtNumeroDaConta;
    // End of variables declaration//GEN-END:variables

    private void limparSelecaoTabelas() {
        tabelaContabancaria.clearSelection();
    }

    private void desativarBotoes() {
        btnEditarConta.setEnabled(false);
        btnExcluirConta.setEnabled(false);
    }

    private void deletarContas() {

    }

    private void atualizarCountContas(int incrementoDecremento) {

    }

    private void atualizarDataHora(LocalDateTime dataLocal) {
        lgdDataHora.setText(dataLocal.format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")));
    }

    private void startRelogio() {
        Timer relogio = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dataLocal = dataLocal.plusSeconds(1);
                atualizarDataHora(dataLocal);
            }
        });

        relogio.start();
    }

}
