/*
 *Componentes:
*   Emanuel Basílio da Silva (20251134040033) 
    Matheus do Nascimento da Silva (20251134040023)
    RENATO ARAUJO GRILO (20251134040018)
    Thiago Tomaz de Araújo (20251134040031)
 */
package br.com.contas.exercicio_02.view;

import br.com.contas.exercicio_02.model.classes.ContaPoupanca;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Thiago Tomaz
 */

public class ContaPoupancaIG extends javax.swing.JDialog {

     private NumberFormat formatoMoedaBrasil;
       
    public ContaPoupancaIG(String iconeLaunch, Locale localBrasil) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(iconeLaunch));
        formatoMoedaBrasil = NumberFormat.getCurrencyInstance(localBrasil);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeContaPoupanca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCadatrarEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNumeroDaConta = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldoContaPoupanca = new javax.swing.JFormattedTextField();
        txtSaldoContaPoupaca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conta poupança");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Saldo da poupança:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome:");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Saldo");

        txtNomeContaPoupanca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeContaPoupancaActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Número da conta:");

        btnCadatrarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/check.png"))); // NOI18N
        btnCadatrarEditar.setText("Cadastrar Conta");
        btnCadatrarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadatrarEditarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setMaximumSize(new java.awt.Dimension(121, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(121, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        try {
            txtNumeroDaConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("com dígito verificador");

        txtSaldoContaPoupanca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtSaldoContaPoupanca.setText("R$ 0,00");

        txtSaldoContaPoupaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtSaldoContaPoupaca.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadatrarEditar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSaldoContaPoupaca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSaldoContaPoupanca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldoContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSaldoContaPoupaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadatrarEditar)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeContaPoupancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeContaPoupancaActionPerformed

    private void btnCadatrarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadatrarEditarActionPerformed

        if (!txtNomeContaPoupanca.getText().trim().toUpperCase().isEmpty() && !txtSaldoContaPoupanca.getText().trim().isEmpty() && !txtSaldoContaPoupaca.getText().trim().isEmpty()) {
            if (txtNumeroDaConta.getText().trim().length() == 8) {
                double saldo = Double.parseDouble(txtSaldoContaPoupanca.getText().trim().replace("R$", "").replace(" ","").replace(".", "").replace(",", "."));
                double saldoDaPoupanca = Double.parseDouble(txtSaldoContaPoupaca.getText().trim().replace("R$", "").replace(" ","").replace(".", "").replace(",", "."));

                if (saldo==0) saldo=0;
                if (saldoDaPoupanca==0) saldoDaPoupanca = 0;
                
                if (saldo >= 0 && saldoDaPoupanca >= 0) {
                    cp = new ContaPoupanca();
                    cp.setNumeroConta(txtNumeroDaConta.getText().trim());
                    cp.setNome(txtNomeContaPoupanca.getText().trim().toUpperCase());
                    cp.setSaldo(saldo);
                    cp.setSaldoPoupanca(saldoDaPoupanca);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor, preencha o saldo e/ou o saldo da poupança com valor a partir de R$ 0 reais!");

                }
            } else {
                JOptionPane.showMessageDialog(this, "O campo numero da conta tem que estar completamente preenchido");
                txtNumeroDaConta.setBorder(new LineBorder(Color.RED, 2));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, verifique se todos os campos estão preenchidos!");

        }


    }//GEN-LAST:event_btnCadatrarEditarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        if (cp != null) {
            setTitle(getTitle() + "  - Editar Conta poupança");
            txtNumeroDaConta.setText(cp.getNumeroConta().trim());
            txtNumeroDaConta.setEnabled(false);
            txtNomeContaPoupanca.setText(cp.getNome());
            txtSaldoContaPoupanca.setText(formatoMoedaBrasil.format(cp.getSaldo()));
            txtSaldoContaPoupaca.setText(formatoMoedaBrasil.format(cp.getSaldoPoupanca()));
            btnCadatrarEditar.setText("Atualizar Conta");
            cp = null;
        }
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadatrarEditar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomeContaPoupanca;
    private javax.swing.JFormattedTextField txtNumeroDaConta;
    private javax.swing.JFormattedTextField txtSaldoContaPoupaca;
    private javax.swing.JFormattedTextField txtSaldoContaPoupanca;
    // End of variables declaration//GEN-END:variables

    private ContaPoupanca cp = null;

    public void setContaPoupanca(ContaPoupanca cp) {
        this.cp = cp;
    }

    public ContaPoupanca getContaPoupanca() {
        return cp;
    }
}
