/*
 *Componentes:
*   Emanuel Basílio da Silva (20251134040033) 
    Matheus do Nascimento da Silva (20251134040023)
    RENATO ARAUJO GRILO (20251134040018)
    Thiago Tomaz de Araújo (20251134040031)
 */
package br.com.contas.exercicio_02.view;

import br.com.contas.exercicio_02.controller.ContaBancariaController;
import br.com.contas.exercicio_02.model.classes.ContaBancaria;
import br.com.contas.exercicio_02.model.classes.OperacaoBancaria;
import br.com.contas.exercicio_02.model.enums.EnumValidacaoCampos;
import br.com.contas.exercicio_02.model.exception.NuloVazioInesxistenteException;
import br.com.contas.exercicio_02.model.exception.CampoSizeInvalidoException;
import br.com.contas.exercicio_02.model.exception.CaractereInvalidoEspacoBrancoException;
import br.com.contas.exercicio_02.model.exception.DoubleFormatClassCastException;
import br.com.contas.exercicio_02.model.util.ConfigDefaultMoedaBR;
import br.com.contas.exercicio_02.model.util.ConfigDefaultSistema;
import br.com.contas.exercicio_02.model.util.ConverterDouble;
import br.com.contas.exercicio_02.model.util.Mensagens;
import br.com.contas.exercicio_02.model.util.ValidarValores;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import javax.swing.JFrame;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Thiago Tomaz
 */
public class ContaBancariaDepositarDebitar extends javax.swing.JDialog {

    /**
     * Creates new form OperacoesContaPoupanca
     */
    private String numeroDaConta;
    private double valorCreditado;
    private int tipoOperacao;

    private OperacaoBancaria operacoesBancarias;
    private ContaBancariaController contasBancariasController;
    private ContaBancaria contaBancaria;

    public ContaBancariaDepositarDebitar(JFrame parent, boolean modal, OperacaoBancaria operacoesBancarias, String titulo, ContaBancariaController contasBancariasController, ContaBancaria contaBancaria) {
        super(parent, modal);
        initComponents();
        setIconImage(ConfigDefaultSistema.getICONE_SISTEMA());

        this.operacoesBancarias = operacoesBancarias;
        this.contaBancaria = contaBancaria;
        this.contasBancariasController = contasBancariasController;

        btnSalvarOperacao.setText("Realizar " + this.operacoesBancarias.getDescricaoOperacao());
        setTitle(titulo);

        lgdDepositoDebito.setText("Valor a " + this.operacoesBancarias.getDescricaoOperacao() + ":");

        NumberFormatter numberFormatter = new NumberFormatter(ConfigDefaultMoedaBR.moeda_default_br());
        setAlwaysOnTop(false);

        txtValorCreditoDebito.setFormatterFactory(new DefaultFormatterFactory(numberFormatter));
        txtValorCreditoDebito.setValue(0.00);
        //objetivo do polimorfismo eliminar tudo isso 
        /* switch (tipoOperacao) {
            case 1:
                setTitle(getTitle() + " | Depositar");
                break;
            case 2:
                setTitle(getTitle() + " | Debitar da conta para o saldo da poupança");
                lgdDepositoDebito.setText("Valor a débitar:");
                break;
            case 3:
                setTitle(getTitle() + " | Debitar");
                lgdDepositoDebito.setText("Valor a débitar:");
                break;
            case 4:
                setTitle(getTitle() + " | Debitar do saldo da poupança para a conta");
                lgdDepositoDebito.setText("Valor do saldo da poupança:");
                break;
            case 5:
                setTitle("Conta Corrente | Depositar");
                break;
            case 6:
                setTitle("Conta Corrente | Debitar");
                lgdDepositoDebito.setText("Valor a debitar:");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro no tipo de operação");
                dispose();
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitularConta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNumeroConta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTipoConta = new javax.swing.JLabel();
        lgdDepositoDebito = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvarOperacao = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNumeroDaConta = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorCreditoDebito = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conta poupança");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dados da Conta");

        lblTitularConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTitularConta.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Titular:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Número da conta:");

        lblNumeroConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNumeroConta.setText("-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de conta:");

        lblTipoConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoConta.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(lblTitularConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(lblNumeroConta, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(lblTipoConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(lblTitularConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(lblNumeroConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(lblTipoConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        lgdDepositoDebito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lgdDepositoDebito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lgdDepositoDebito.setText("Valor do depósito");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Número da conta:");

        btnSalvarOperacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvarOperacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/check.png"))); // NOI18N
        btnSalvarOperacao.setText("Realizar Crédito");
        btnSalvarOperacao.setEnabled(false);
        btnSalvarOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarOperacaoActionPerformed(evt);
            }
        });
        btnSalvarOperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarOperacaoKeyPressed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(121, 28));
        btnCancelar.setMinimumSize(new java.awt.Dimension(121, 28));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        try {
            txtNumeroDaConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroDaConta.setFocusTraversalPolicyProvider(true);
        txtNumeroDaConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumeroDaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDaContaActionPerformed(evt);
            }
        });
        txtNumeroDaConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroDaContaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroDaContaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("com dígito verificador");

        txtValorCreditoDebito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtValorCreditoDebito.setEnabled(false);
        txtValorCreditoDebito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValorCreditoDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCreditoDebitoActionPerformed(evt);
            }
        });
        txtValorCreditoDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorCreditoDebitoKeyPressed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lgdDepositoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgdDepositoDebito)
                    .addComponent(txtValorCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarOperacao)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarOperacaoActionPerformed

        salvarContaBancaria();

    }//GEN-LAST:event_btnSalvarOperacaoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        OperacaoVazia();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisarContaBancaria();

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        OperacaoVazia();
    }//GEN-LAST:event_formWindowClosing

    private void txtNumeroDaContaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDaContaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDaContaKeyReleased

    private void txtNumeroDaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDaContaActionPerformed
        pesquisarContaBancaria();
    }//GEN-LAST:event_txtNumeroDaContaActionPerformed

    private void txtNumeroDaContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDaContaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNumeroDaConta.postActionEvent();
        }
    }//GEN-LAST:event_txtNumeroDaContaKeyPressed

    private void txtValorCreditoDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCreditoDebitoActionPerformed
        btnSalvarOperacao.requestFocus();
    }//GEN-LAST:event_txtValorCreditoDebitoActionPerformed

    private void txtValorCreditoDebitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCreditoDebitoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValorCreditoDebito.postActionEvent();
        }
    }//GEN-LAST:event_txtValorCreditoDebitoKeyPressed

    private void btnSalvarOperacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarOperacaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvarContaBancaria();
        }
    }//GEN-LAST:event_btnSalvarOperacaoKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarOperacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumeroConta;
    private javax.swing.JLabel lblTipoConta;
    private javax.swing.JLabel lblTitularConta;
    private javax.swing.JLabel lgdDepositoDebito;
    private javax.swing.JFormattedTextField txtNumeroDaConta;
    private javax.swing.JFormattedTextField txtValorCreditoDebito;
    // End of variables declaration//GEN-END:variables

    private void OperacaoVazia() {
        contaBancaria = null;
        operacoesBancarias = null;
    }

    private void pesquisarContaBancaria() {
        btnPesquisar.requestFocus();
        boolean exibir = false;

        contasBancariasController.consultarViewContaBancariaNumeroDaConta(txtNumeroDaConta.getText(), this);


    }

    public ContaBancaria getContaBancaria() {
        return contaBancaria;
    }

    public OperacaoBancaria getOperacaobancaria() {
        return operacoesBancarias;
    }

    public void contaValida(ContaBancaria conta) {
        this.contaBancaria = conta;
        lblNumeroConta.setText(contaBancaria.getNumeroConta());
        lblTipoConta.setText(contaBancaria.getDescricaoConta());
        lblTitularConta.setText(contaBancaria.getNome());
        
        btnSalvarOperacao.setEnabled(true);
        txtValorCreditoDebito.setEnabled(true);
        txtValorCreditoDebito.requestFocus();
        
    }

    public void contaInvalida(ContaBancaria contaBancaria) {
        contaBancaria=contaBancaria;
        lblNumeroConta.setText("-");
        lblTipoConta.setText("-");
        lblTitularConta.setText("-");
        btnSalvarOperacao.setEnabled(false);
        txtValorCreditoDebito.setEnabled(false);
    }

    private void salvarContaBancaria() {
        btnSalvarOperacao.requestFocus();
        valorCreditado = 0;

        try {
            ValidarValores.isNullEmpity(txtNumeroDaConta.getText().trim(), "Número da conta inválido ou vazio!");
            ValidarValores.isNullEmpity(txtValorCreditoDebito.getText().trim(), "O valor a " + operacoesBancarias.getDescricaoOperacao() + " inválido ou vazio!");
            ValidarValores.caractereInvalidoEspacoBranco(txtNumeroDaConta.getText());
            ValidarValores.caractereInvalidoEspacoBranco(txtValorCreditoDebito.getText());
            ValidarValores.validarTamanho(txtNumeroDaConta.getText().trim(), EnumValidacaoCampos.NUMERO_CONTA);
            valorCreditado = ConverterDouble.converterObjectToDouble(txtValorCreditoDebito.getValue());

        } catch (NuloVazioInesxistenteException | CampoSizeInvalidoException | DoubleFormatClassCastException | CaractereInvalidoEspacoBrancoException ex) {
            Mensagens.error(ex.getMessage());
            return;
        }

        //salvando uma operaçao que vai ser verificada no service 
        operacoesBancarias.setContaDestino(txtNumeroDaConta.getText());
        operacoesBancarias.setContaOrigem("000000-0");
        operacoesBancarias.setValorTransferido(valorCreditado);
        operacoesBancarias.setDataTransferencia(LocalDateTime.now());

        dispose();
    }

}
