/*
 *Componentes:
*   Emanuel Basílio da Silva (20251134040033) 
    Matheus do Nascimento da Silva (20251134040023)
    RENATO ARAUJO GRILO (20251134040018)
    Thiago Tomaz de Araújo (20251134040031)
 */
package br.com.contas.exercicio_02.view;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Thiago Tomaz
 */
public class ContasDepositarDebitarIG extends javax.swing.JDialog {

    /**
     * Creates new form OperacoesContaPoupanca
     */
    private String numeroDaConta;
    private double valorCreditado;
    private int tipoOperacao;

    public ContasDepositarDebitarIG(String iconeLaunch, boolean modal, int tipoOperacao) {

        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(iconeLaunch));
        numeroDaConta = null;
        valorCreditado = 0;
        this.tipoOperacao = tipoOperacao;
        switch (tipoOperacao) {
            case 1:
                setTitle(getTitle() + " | Depositar");
                break;
            case 2:
                setTitle(getTitle() + " | Debitar da conta para o saldo da poupança");
                lgdDepositoDebito.setText("Valor a débitar:");
                break;
            case 3:
                setTitle(getTitle() + " | Debitar");
                lgdDepositoDebito.setText("Valor a débitar:");
                break;
            case 4:
                setTitle(getTitle() + " | Debitar do saldo da poupança para a conta");
                lgdDepositoDebito.setText("Valor do saldo da poupança:");
                break;
            case 5:
                setTitle("Conta Corrente | Depositar");
                break;
            case 6:
                setTitle("Conta Corrente | Debitar");
                lgdDepositoDebito.setText("Valor a debitar:");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Erro no tipo de operação");
                dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lgdDepositoDebito = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCadatrarEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNumeroDaConta = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldoContaPoupanca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conta poupança");

        lgdDepositoDebito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lgdDepositoDebito.setText("Valor do depósito");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Número da conta:");

        btnCadatrarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/check.png"))); // NOI18N
        btnCadatrarEditar.setText("Efetuar Operação");
        btnCadatrarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadatrarEditarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setMaximumSize(new java.awt.Dimension(121, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(121, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        try {
            txtNumeroDaConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroDaConta.setFocusTraversalPolicyProvider(true);
        txtNumeroDaConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("com dígito verificador");

        txtSaldoContaPoupanca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtSaldoContaPoupanca.setText("R$ 0,00");
        txtSaldoContaPoupanca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadatrarEditar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(lgdDepositoDebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaldoContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgdDepositoDebito)
                    .addComponent(txtSaldoContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadatrarEditar)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadatrarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadatrarEditarActionPerformed

        if (!txtSaldoContaPoupanca.getText().trim().isEmpty()) {
            if (txtNumeroDaConta.getText().trim().length() == 8) {
                numeroDaConta = txtNumeroDaConta.getText().trim();
                valorCreditado = Double.parseDouble(txtSaldoContaPoupanca.getText().trim().replace("R$", "").replace(" ", "").replace(".", "").replace(",", "."));
                
                if(valorCreditado==0) valorCreditado=0;
                
               if (valorCreditado > 0) {
                    dispose();
                } else {
                    valorCreditado = 0;
                    numeroDaConta = null;
                    JOptionPane.showMessageDialog(null, "Por favor, preencha campo [ "+lgdDepositoDebito.getText()+" ] com valor acima de R$ 0 reais!");
                }

            } else {
                JOptionPane.showMessageDialog(this, "O campo numero da conta tem que estar completamente preenchido");
                txtNumeroDaConta.setBorder(new LineBorder(Color.RED, 2));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, verifique se todos os campos estão preenchidos!");

        }

    }//GEN-LAST:event_btnCadatrarEditarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadatrarEditar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lgdDepositoDebito;
    private javax.swing.JFormattedTextField txtNumeroDaConta;
    private javax.swing.JFormattedTextField txtSaldoContaPoupanca;
    // End of variables declaration//GEN-END:variables

    public double getValorCreditado() {
        return valorCreditado;
    }

    public void setValorCreditado(double valorCreditado) {
        this.valorCreditado = valorCreditado;
    }

    public String getNumeroDaConta() {
        return numeroDaConta;
    }

    public void setNumeroDaConta(String numeroDaConta) {
        this.numeroDaConta = numeroDaConta;
    }

}
