/*
 *Componentes:
*   Emanuel Basílio da Silva (20251134040033) 
    Matheus do Nascimento da Silva (20251134040023)
    RENATO ARAUJO GRILO (20251134040018)
    Thiago Tomaz de Araújo (20251134040031)
 */
package br.com.contas.exercicio_02.view;

import br.com.contas.exercicio_02.model.exception.CampoNuloVazioException;
import br.com.contas.exercicio_02.model.exception.CampoSizeInvalidoException;
import br.com.contas.exercicio_02.model.exception.CaractereInvalidoEspacoBrancoException;
import br.com.contas.exercicio_02.model.classes.ContaBancaria;
import br.com.contas.exercicio_02.model.enums.EnumValidacaoCampos;
import br.com.contas.exercicio_02.model.exception.DoubleFormatClassCastException;
import br.com.contas.exercicio_02.model.exception.NumeroFormatoException;
import br.com.contas.exercicio_02.model.util.ConfigDefaultMoedaBR;
import br.com.contas.exercicio_02.model.util.ConfigDefaultSistema;
import br.com.contas.exercicio_02.model.util.ConverterDouble;
import br.com.contas.exercicio_02.model.util.Mensagens;
import br.com.contas.exercicio_02.model.util.ValidationValores;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.border.LineBorder;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Thiago Tomaz
 */
public class ContasBancariaEditarCadastrar extends javax.swing.JDialog {

    /**
     * Creates new form ContaCorrenteIG
     */
    private ContaBancaria contaBancaria;

    public ContasBancariaEditarCadastrar(JFrame parent, boolean modal, ContaBancaria contaBancaria) {
        super(parent, modal);
        initComponents();
        setIconImage(ConfigDefaultSistema.getICONE_SISTEMA());
        this.contaBancaria = contaBancaria;

        NumberFormatter numberFormatter = new NumberFormatter(ConfigDefaultMoedaBR.moeda_default_br());
        setAlwaysOnTop(false);

        //A magica do polimorfismo, funcionando corretamente, sem if's limpo e funcional;
        txtNumeroDaConta.setText(this.contaBancaria.getNumeroConta());
        txtNomeContaCorrente.setText(this.contaBancaria.getNome());

        txtInfoAdicionalConta.setFormatterFactory(new DefaultFormatterFactory(numberFormatter));
        txtInfoAdicionalConta.setValue(this.contaBancaria.getInfoAdicionalConta());

        txtSaldoContaCorrente.setFormatterFactory(new DefaultFormatterFactory(numberFormatter));
        txtSaldoContaCorrente.setValue(this.contaBancaria.getSaldo());

        txtInfoAdicionalConta.setEnabled(contaBancaria.isInfoAdicionalConta());
        lblDescricaoInfoAdicionalCampo.setText(this.contaBancaria.getDescricaoInfoAdicionalCampo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDescricaoInfoAdicionalCampo = new javax.swing.JLabel();
        jblSaldo = new javax.swing.JLabel();
        txtNomeContaCorrente = new javax.swing.JTextField();
        btnSalvarEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroDaConta = new javax.swing.JFormattedTextField();
        txtInfoAdicionalConta = new javax.swing.JFormattedTextField();
        txtSaldoContaCorrente = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome Completo:");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDescricaoInfoAdicionalCampo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricaoInfoAdicionalCampo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescricaoInfoAdicionalCampo.setText("Limite Conta Corrente [R$]:");

        jblSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblSaldo.setText("Saldo[R$]:");

        txtNomeContaCorrente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeContaCorrenteActionPerformed(evt);
            }
        });

        btnSalvarEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/check.png"))); // NOI18N
        btnSalvarEditar.setText("Cadastrar conta");
        btnSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setMaximumSize(new java.awt.Dimension(121, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(121, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Número da conta:");

        try {
            txtNumeroDaConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroDaConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtInfoAdicionalConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtInfoAdicionalConta.setText("0.00");
        txtInfoAdicionalConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSaldoContaCorrente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("com dígito verificador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescricaoInfoAdicionalCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jblSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInfoAdicionalConta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addComponent(txtSaldoContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblSaldo)
                    .addComponent(txtSaldoContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoInfoAdicionalCampo)
                    .addComponent(txtInfoAdicionalConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarEditar)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeContaCorrenteActionPerformed

    }//GEN-LAST:event_txtNomeContaCorrenteActionPerformed


    private void btnSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditarActionPerformed
        /*por que não lançar um exception para o controller tratar?
        pois aqui não faz sentido lançar uma exception para o Controller, já que
        a janela ainda está aberta, e o usuário deve corrigir as informções.   
         */
        btnSalvarEditar.hasFocus();
        double saldo, valorInfoAdicional;
        try {
            //validar campos vazios ou nullos
            ValidationValores.isNullEmpity(txtNumeroDaConta.getText().trim(), "O Campo [ número da conta ] da conta não esta preenchido");
            ValidationValores.isNullEmpity(txtNomeContaCorrente.getText().trim(), "O Campo [ nome ] da conta não esta preenchido");
            ValidationValores.isNullEmpity(txtSaldoContaCorrente.getText().trim(), "O Campo [ saldo ] da conta não esta preenchido");
            ValidationValores.isNullEmpity(txtInfoAdicionalConta.getText().trim(), "O Campo [ Informa~ ] da conta não esta preenchido");
            //Verificar se o campo não aceite caracteres vazios entre os números
            ValidationValores.caractereInvalidoEspacoBranco(txtNumeroDaConta.getText());
            //validar campo numero da conta para que ele tenho os 8 caracteres
            ValidationValores.validarTamanho(txtNumeroDaConta.getText(), EnumValidacaoCampos.NUMERO_CONTA);
            //converter os valores do campo saldo e valor adicional para doubles
            saldo = ConverterDouble.converterObjectToDouble(txtSaldoContaCorrente.getValue());
            valorInfoAdicional = contaBancaria.isInfoAdicionalConta() ? ConverterDouble.converterObjectToDouble(txtInfoAdicionalConta.getValue()) : 0;
            
        } catch (CampoNuloVazioException | CaractereInvalidoEspacoBrancoException | DoubleFormatClassCastException  ex) {
            Mensagens.error(ex.getMessage());
            return;
        } catch (CampoSizeInvalidoException ex) {
            Mensagens.error(ex.getMessage());
            txtNumeroDaConta.setBorder(new LineBorder(Color.RED, 2));
            return;//aqui se interrompe o fluxo
        }
        //implementar o NumberFormat para trabalhar com moedas

        

        // Correção caso o usuario digite -0, por acidente ou para testar o simulador
        // Esse caso ocorreu comigo e pesquisando descrobri essa tecnica
        contaBancaria.setNumeroConta(txtNumeroDaConta.getText().trim());
        contaBancaria.setNome(txtNomeContaCorrente.getText().trim().toUpperCase());
        contaBancaria.setSaldo(saldo);
        contaBancaria.setInfoAdicionalConta(valorInfoAdicional);

        dispose();

    }//GEN-LAST:event_btnSalvarEditarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fecharView();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded

    }//GEN-LAST:event_jLabel1AncestorAdded

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarEditar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblSaldo;
    private javax.swing.JLabel lblDescricaoInfoAdicionalCampo;
    private javax.swing.JFormattedTextField txtInfoAdicionalConta;
    private javax.swing.JTextField txtNomeContaCorrente;
    private javax.swing.JFormattedTextField txtNumeroDaConta;
    private javax.swing.JFormattedTextField txtSaldoContaCorrente;
    // End of variables declaration//GEN-END:variables

    public ContaBancaria getContaBancaria() {
        return contaBancaria;
    }

    private void fecharView() {
        dispose();
    }

    public void setNomeDoBotao(String string) {
        btnSalvarEditar.setText(string);
    }
}
