/*
 *Componentes:
*   Emanuel Basílio da Silva (20251134040033) 
    Matheus do Nascimento da Silva (20251134040023)
    RENATO ARAUJO GRILO (20251134040018)
    Thiago Tomaz de Araújo (20251134040031)
 */
package br.com.contas.exercicio_02.view;

import br.com.contas.exercicio_02.controller.ContaBancariaController;
import br.com.contas.exercicio_02.model.classes.ContaBancaria;
import br.com.contas.exercicio_02.model.enums.EnumValidacaoCampos;
import br.com.contas.exercicio_02.model.exception.CampoSizeInvalidoException;
import br.com.contas.exercicio_02.model.exception.CaractereInvalidoEspacoBrancoException;
import br.com.contas.exercicio_02.model.exception.DoubleFormatClassCastException;
import br.com.contas.exercicio_02.model.exception.NuloVazioInesxistenteException;
import br.com.contas.exercicio_02.model.util.ConfigDefaultMoedaBR;
import br.com.contas.exercicio_02.model.util.ConfigDefaultSistema;
import br.com.contas.exercicio_02.model.util.ConverterDouble;
import br.com.contas.exercicio_02.model.util.Mensagens;
import br.com.contas.exercicio_02.model.util.ValidarValores;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Thiago Tomaz
 */
public class TransferenciaEntreContasBancariasIG extends javax.swing.JDialog {

    /**
     * Creates new form TransferenciaEntreContasCorrentes
     */
    private ContaBancariaController contaBancariaController;
    private ContaBancaria[] contaBancarias = new ContaBancaria[2];
    private double valorTransferencia = 0;
    
    public TransferenciaEntreContasBancariasIG(java.awt.Frame parent, boolean modal, ContaBancariaController contaBancariaController, String titulo) {
        super(parent, modal);
        initComponents();
        setIconImage(ConfigDefaultSistema.getICONE_SISTEMA());
        
        this.contaBancariaController = contaBancariaController;
        NumberFormatter numberFormatter = new NumberFormatter(ConfigDefaultMoedaBR.moeda_default_br());
        setAlwaysOnTop(false);
        
        txtValorTransferencia.setFormatterFactory(new DefaultFormatterFactory(numberFormatter));
        
        setTitle(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroDaContaOrigem = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroDaContaDestino = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValorTransferencia = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        btnSalvarEditar = new javax.swing.JButton();
        lblContaDestinoIcone = new javax.swing.JLabel();
        lblContaOrigemIcone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transferência entre contas correntes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Valor:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Conta de origem:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("com dígito verificador");

        try {
            txtNumeroDaContaOrigem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroDaContaOrigem.setFocusTraversalPolicyProvider(true);
        txtNumeroDaContaOrigem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("com dígito verificador");

        try {
            txtNumeroDaContaDestino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroDaContaDestino.setFocusTraversalPolicyProvider(true);
        txtNumeroDaContaDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumeroDaContaDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Conta de destino:");

        txtValorTransferencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtValorTransferencia.setText("0,00");
        txtValorTransferencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setMaximumSize(new java.awt.Dimension(121, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(121, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSalvarEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icones_32/check.png"))); // NOI18N
        btnSalvarEditar.setText("Transferir");
        btnSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumeroDaContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(txtValorTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(txtNumeroDaContaDestino)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContaDestinoIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContaOrigemIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDaContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContaOrigemIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblContaDestinoIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDaContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarEditar)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fecharJanela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditarActionPerformed
        
        btnSalvarEditar.requestFocus();
        
        try {
            ValidarValores.isNullEmpity(txtNumeroDaContaOrigem.getText(), "Campo número de origem vazio");
            ValidarValores.isNullEmpity(txtNumeroDaContaDestino.getText(), "Campo número de Destino vazio");
            ValidarValores.isNullEmpity(txtValorTransferencia.getValue().toString(), "Campo valor transferir vazio");
            
            ValidarValores.caractereInvalidoEspacoBranco(txtNumeroDaContaOrigem.getText());
            ValidarValores.caractereInvalidoEspacoBranco(txtNumeroDaContaDestino.getText());
            ValidarValores.validarTamanho(txtNumeroDaContaDestino.getText().trim(), EnumValidacaoCampos.NUMERO_CONTA);
            ValidarValores.validarTamanho(txtNumeroDaContaOrigem.getText().trim(), EnumValidacaoCampos.NUMERO_CONTA);
            
            valorTransferencia = ConverterDouble.converterObjectToDouble(txtValorTransferencia.getValue());
            
        } catch (NuloVazioInesxistenteException | DoubleFormatClassCastException | CaractereInvalidoEspacoBrancoException | CampoSizeInvalidoException ex) {
            Mensagens.error(ex.getMessage());
        }
        
        consultarContaBancariaOrigemDestino(txtNumeroDaContaOrigem.getText(), 0);
        consultarContaBancariaOrigemDestino(txtNumeroDaContaDestino.getText(), 1);
                
        dispose();
        

    }//GEN-LAST:event_btnSalvarEditarActionPerformed

    private void ed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ed
        
    }//GEN-LAST:event_ed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fecharJanela();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarEditar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblContaDestinoIcone;
    private javax.swing.JLabel lblContaOrigemIcone;
    private javax.swing.JFormattedTextField txtNumeroDaContaDestino;
    private javax.swing.JFormattedTextField txtNumeroDaContaOrigem;
    private javax.swing.JFormattedTextField txtValorTransferencia;
    // End of variables declaration//GEN-END:variables

    public double getValorTransferencia() {
        return valorTransferencia;
    }
    
    public void setValorTransferencia(double valorTransferencia) {
        this.valorTransferencia = valorTransferencia;
    }
    
    public ContaBancaria[] getContasBancariasOrigemDestino() {
        return contaBancarias;
    }
    
    private void setContaBancaria(ContaBancaria conta, int indice) {
        this.contaBancarias[indice] = conta;
    }
    
    private void consultarContaBancariaOrigemDestino(String codigoContaBancaria, int indiceConta) {
        getConsultarContaBancaria(codigoContaBancaria, indiceConta);
    }
    
    private void getConsultarContaBancaria(String codigoContaBancaria, int indiceConta) {
        contaBancariaController.validarViewContaOrigemDestino(codigoContaBancaria, this, indiceConta);
    }
    
    private void fecharJanela() {
        contaBancarias = null;
        dispose();
    }
    
    public void isContaInValida(ContaBancaria conta, String icone, int indice) {
        setContaBancaria(conta, indice);
        if (indice == 0) {
            lblContaOrigemIcone.setIcon(new ImageIcon(getClass().getResource(icone)));
        } else {
            lblContaDestinoIcone.setIcon(new ImageIcon(getClass().getResource(icone)));
        }
    }
}
